### ISSUE TITLE
Cookie Clicker issue

### ISSUE THREAD

**Issue by heddib** [NiklasEi/cookieclicker-for-gamebox#11]
**Description:**
When you close the gui while you are playing Cookie Clicker (only with the escape key or the key which open your inventory), it mays re-open because of the inventory actualisation but you can take any elements of the inventory.

Moreover if you could do an configurable option to remove the "ordered size" and "waiting size" debug in the console it would be nice.

**Information:**
Server version: Spigot 1.8.8
Plugin version: GameBox 2.1.13

**Comment by NiklasEi** [comment]
I must have forgotten to remove the debug messages, sorry about that.

I will look into the gui issues tomorrow and upload a fixed version without debug messages.
