### ISSUE TITLE
Feature request: Customise the shortened letters for numbers

### ISSUE THREAD

**Issue by heddib** [NiklasEi/cookieclicker-for-gamebox#12]
I suggest you to add an option to customise the letters that shorten the numbers (for instance we could change "B" for "Billion".

**Comment by NiklasEi** [comment]
These names are global for GameBox and thus handled in GameBox and not in CookieClicker itself. For the time being Cookieclicker is just the only game that actually needs these high number names.

I am moving this issue to GameBox.
