### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by NiklasEi** [NiklasEi/cookieclicker-for-gamebox#6]
At the moment the german language file has all the upgrades and buildings in english...  
[lang_de.yml](../tree/master/language/lang_de.yml)

**Comment by AndyYu168** [comment]
Maybe there are quite too much to translate? since German is your mother tongue...

**Comment by NiklasEi** [comment]
Yes
I did the English part already. I don't want to continue with the whole German file now...

I'll be traveling the next week anyway. I'll just do the German translation after that (If no one else does :smile: ).
